# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 30

arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - jaco_joint_1
    - jaco_joint_2
    - jaco_joint_3
    - jaco_joint_4
    - jaco_joint_5
    - jaco_joint_6

fingers_controller:
  type: "position_controllers/GripperActionController"
#  joints:
#    - jaco_joint_finger_1
#    - jaco_joint_finger_2
#    - jaco_joint_finger_3
  joint: jaco_joint_finger_1